name: Cypress Tests and Dashboard Upload

on:
    push:
        branches:
            - main # Adjust this branch name to match your repository's main branch

jobs:
    cypress:
        runs-on: windows-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18 # Choose the Node.js version you want to use

            - name: Install dependencies
              run: npm install

            - name: Run Cypress tests and upload to Cypress Dashboard
              run: |
                  npm run cy-record
              env:
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
